### PR TITLE
fix for broken inference on metadata prop

### LINKED ISSUE #192: Generic Type of Metadata Is Incorrect in nodeRenderer Callback.
**Describe the bug**
The type of `metadata` in `nodeRenderer` is being inferred incorrectly.

**Code That Causes The Issue**
```ts
<TreeView
        data={data}
        className="basic"
        aria-label="basic example tree"
        nodeRenderer={({ element, getNodeProps, level, handleSelect }) => (
            <div {...getNodeProps()} style={{ paddingLeft: 20 * (level - 1) }}>
                {element.name} {element.metadata?.pending}
            </div>
        )}
    />
```

**To Reproduce**
I created a minimal reproduction but you can do the following.
1. Create a tree as outlined in the docs.
2. add the metadata field to any node in your data.
3. attempt to access `metadata` from `element` in the node renderer prop on the tree.

https://codesandbox.io/p/devbox/8rc7df?file=%2Fsrc%2FBasicTreeView.tsx%3A40%2C5-49%2C7

**Expected behavior**
The generic type of `metadata` should be inferred in the same manner as it is in `flattenTree` as shown in my reproduction.

Note:
I am almost certain it is caused by this. 
```ts
interface INode<M extends IFlatMetadata = IFlatMetadata> {
    /** A non-negative integer that uniquely identifies the node */
    id: string | number;
    /** Used to match on key press */
    name: string;
    /** An array with the ids of the children nodes */
    children: (string | number)[];
    /** The parent of the node; null for the root node */
    parent: (string | number) | null;
    /** Used to indicated whether a node is branch to be able load async data onExpand*/
    isBranch?: boolean;
    /** User-defined metadata */
    metadata?: M;
  }

 export interface INodeRendererProps {
    /** The object that represents the rendered node */
    element: INode;
    /** A function which gives back the props to pass to the node */
    getNodeProps: (args?: {
      onClick?: EventCallback;
    }) => IBranchProps | LeafProps;
    /** Whether the rendered node is a branch node */
    isBranch: boolean;
    /** Whether the rendered node is selected */
    isSelected: boolean;
    /** If the node is a branch node, whether it is half-selected, else undefined */
    isHalfSelected: boolean;
    /** If the node is a branch node, whether it is expanded, else undefined */
    isExpanded: boolean;
    /** Whether the rendered node is disabled */
    isDisabled: boolean;
    /** A positive integer that corresponds to the aria-level attribute */
    level: number;
    /** A positive integer that corresponds to the aria-setsize attribute */
    setsize: number;
    /** A positive integer that corresponds to the aria-posinset attribute */
    posinset: number;
    /** Function to assign to the onClick event handler of the element(s) that will toggle the selected state */
    handleSelect: EventCallback;
    /** Function to assign to the onClick event handler of the element(s) that will toggle the expanded state */
    handleExpand: EventCallback;
    /** Function to dispatch actions */
    dispatch: React.Dispatch<TreeViewAction>;
    /** state of the treeview */
    treeState: ITreeViewState;
  }

```
There is no generic being passed to `INodeRenderer` so it uses the default specified in `INode`. You can even see that `metadata` uses the default type in the repro. It would also explain why there is no type error.

I also reproduced the type issue here:
https://www.typescriptlang.org/play/?ssl=37&ssc=1&pln=1&pc=1#code/C4TwDgpgBAkgYgGwIbALIWEgJipUC8UAShAMYD2ATlgDwBQUUAzsJQJYB2A5gDQPOtOXKAB8oHAK4BbAEYRKoqDPLkEEJB0USOWCADNOELIskIEdAHwBuOnU7B5epKWgwAcuV01UUCAA8HHSZYRBR0TBxMAhDkNAxsXAsoAG9+RgB6ACpMqABBcXIOAFoOCC4UNgA3aHsy+ShgAAsUKG02AEcJCAQQKDZdDmA2AwhgpugOT2hM9LS+rAAuAXZuE2k5ShtGDOyoAFUmIwbyKCkUUkaoQqgAawhesEpR4Jm5jiQpCCWWFa4t7ayOVymiQlEoSF6AHc2E0Go0alhguQ9HDoBc2AgsE9NJNdC9ZtsoOjMdilgAKH5CNayeQASgA2gBdf47HIAFXhUDAoIggyuKPGBV0VnEEjMUD0VFRUEoKmAQumBO23OxwHJlNWYkkNMotLWZhZUEB+0OxmAJ04WDYpBQR0h8PGCjwuJqwRk4I4F2OSmgSBkaigCHI2CgSCYIE9UEieEKAFE-NydK9CWwmAAhD0XAD8S2UqnUHENxoO8iKugMpWMnwiuCgye21YSmBzUFQ-wAvrZGLVKE4XLAPLoSDp5PIAAqysDBVKE40c6DkGQAKzI8qaLSej1GvOAY052N0T2MLrrSsY3Qgn0GS3cUw7tjoFA4LAaozVA6mw8P48nwUIyQvK931Sd5PiWAByBwWHAnhG2jJZklFKQlgARgABigds+H6JYACIUNwvhiSxXkliZPgVR3JZTHMdtOzodJ0ncAA1XIABkYAAESgNNYwACVyZiYAAeSIOhQEgKA2RQ6IJIgZFXxYelwMAndwMZZS4NwdTfACXlERSbVqPWeR2ygLMGkoLooGoiBqkoB9GCAA

### PR DESCRIPTION
**Pull request by mreid21**
This should provide type inference for `element.metadata`. I checked to see that the type was correct when passing metadata. However, I don't know too much about `propTypes` since I only really use typescript with React. Please let me know if there is any issues with this approach.

fixes #192

### CODE REVIEW

**Comment by mreid21** [comment]
@mellis481

**Comment by dgreene1** [comment]
@mreid21 unless I’m mistaken, I don’t see any code that does a type assertion in that there is no code that throws if the ref is not present.

**Comment by mreid21** [comment]
```ts
function genericForwardRef<T, P = Record<string, unknown>>(
    render: (props: P, ref: React.Ref<T>) => JSX.Element
  ): (props: P & React.RefAttributes<T>) => JSX.Element {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    return React.forwardRef(render) as any;
  }
  ```
I'm not sure what you mean, maybe I'm misunderstanding? I do a type assertion here. If I perform the type assertion directly on `forwardRef` propTypes throws an error because `propTypes` does not exist on my asserted type. To fix this, I rewrite `forwardRef` so that the generic from ITreeViewProps is captured. Since this is all done at the type level I know none of the functionality should change.

**Comment by mreid21** [comment]
One downside is that the correct type for `metadata` cannot be inferred in flatten tree. So the only reliable way is to set the generic on `flattenTree`. It will be inferred in the component from that point though.

**Comment by mreid21** [comment]
@dgreene1  @mellis481  I updated the PR to use a type assertion. You can see that if you add the `metadata` property to any of the example tests that the type of `metadata` will now be correctly inferred by `nodeRenderer`. Please take a look, as this change will be super helpful for typescript consumers and shouldn't have any impact on runtime performance or js consumers.

**Comment by ivasilov** [comment]
Plus one on this PR, I have to do an ugly hack to achieve the same thing:
```
export interface NodeRendererProps<M extends IFlatMetadata>
  extends Omit<INodeRendererProps, 'element'> {
  element: INode<M>
}

interface TreeViewProps<M extends IFlatMetadata> extends Omit<ITreeViewProps, 'nodeRenderer'> {
  data: INode<M>[]
  nodeRenderer: (props: NodeRendererProps<M>) => React.ReactNode
}

function TreeView<M extends IFlatMetadata>(props: TreeViewProps<M>) {
  return <TreeViewPrimitive {...(props as any)} />
}
```

**Comment by mellis481** [comment]
@mreid21 Can you address the failing PR check please? I'll try to have my team review/merge your PR soon. Thanks.

**Comment by mreid21** [comment]
I added the missing generics for Node. All the tests are passing now.

**Comment by danielbuechele** [comment]
Thanks for fixing this. @mellis481 I would love to see this merged!

File: src/TreeView/types.ts [hunk 1]
```diff
@@ -33,9 +33,9 @@ export type EventCallback = <T, E>(
     metadata?: M;
   }
 
-  export interface INodeRendererProps {
+  export interface INodeRendererProps<M extends IFlatMetadata> {
```
Comment (MehmetYararVX) [inline src/TreeView/types.ts]: We could be consistent in using the default type unless there is a specific reason not to:
`<M extends IFlatMetadata = IFlatMetadata>`

File: src/TreeView/node.tsx [hunk 2]
```diff
@@ -329,7 +330,7 @@ export const NodeGroup = ({
           expandedIds={expandedIds}
           baseClassNames={baseClassNames}
           key={`${x}-${typeof x}`}
-          element={getTreeNode(data, x)}
+          element={getTreeNode(data, x) as INode<M>}
```
Comment (MehmetYararVX) [inline src/TreeView/node.tsx]: We could avoid type-casting here:

```ts
export const getTreeNode = <M extends IFlatMetadata>(
  data: INode<M>[],
  id: NodeId
): INode<M> => {
  // ...
};
```

File: src/TreeView/node.tsx
Comment (MehmetYararVX) [inline src/TreeView/node.tsx:1]: We could be consistent in using the default type unless there is a specific reason not to:

- `export interface INodeProps<M extends IFlatMetadata = IFlatMetadata>`
- `export interface INodeGroupProps<M extends IFlatMetadata = IFlatMetadata>`
- `const removeIrrelevantGroupProps = <M extends IFlatMetadata = IFlatMetadata>(`
- `export const Node = <M extends IFlatMetadata = IFlatMetadata>(`
- `export const NodeGroup = <M extends IFlatMetadata = IFlatMetadata>({`

File: src/TreeView/index.tsx [hunk 3]
```diff
@@ -669,9 +669,15 @@ const TreeView = React.forwardRef<HTMLUListElement, ITreeViewProps>(
           />
         ))}
       </ul>
-    );
+    )
   }
-);
+
+
+  const TreeView = React.forwardRef(TreeViewInner) as <T extends IFlatMetadata>(
```
Comment (MehmetYararVX) [inline src/TreeView/index.tsx]: Could we try w/o creating `TreeViewInner`?

```tsx
const TreeView = React.forwardRef(function TreeView<
  M extends IFlatMetadata = IFlatMetadata
>({ ...props }: ITreeViewProps<M>, ref: React.ForwardedRef<HTMLUListElement>) {
  return (
    <ul role="tree" ref={innerRef}>
      {/* ... */}
    </ul>
  );
});
```

Let's also try removing this comment along with this change:

`//@ts-expect-error type assertion for ts`

**Review by MehmetYararVX — COMMENTED** [review]
@mreid21, could you please evaluate/implement my comments?

cc: @mellis481, @dgreene1

File: src/TreeView/types.ts (hunk 1 above)
Comment (mreid21) [reply src/TreeView/types.ts]: I added this. Additionally, should I assume that any function that accepts `INode` should instead be generic `INode<M>`? For instance this function and others that will not be used by consumers of the package.
```ts
export const isBranchSelectedAndHasSelectedDescendants = (
  data: INode[],
  elementId: NodeId,
  selectedIds: Set<NodeId>
) => {
  return (
    isBranchNode(data, elementId) &&
    selectedIds.has(elementId) &&
    getDescendants(data, elementId, new Set<number>()).some((item) =>
      selectedIds.has(item)
    )
  );
};
```

Comment (mreid21) [reply src/TreeView/types.ts]: Mainly asking because I'm not sure whether y'all want that for consistency since these utility functions don't make use of the metadata property.

**Comment by MehmetYararVX** [comment]
@mreid21, thanks for evaluating my comments and updating the PR.

> should I assume that any function that accepts INode should instead be generic INode<M>

No, because INode already has a generic with a default type. As you mentioned, not all functions are used by the consumer directly, so we can skip as such. But I'd avoid type-casting where possible, e.g., `getTreeNode` and making too many changes at once.

On the other hand, I've found it advisable to use the default type in Node and NodeGroup components since we also used a default type in the TreeView component.

@mellis481, @dgreene1, this PR looks good to me. Let's see if checks pass after changes.

**Review by mellis481 — APPROVED** [review]

**Comment by mellis481** [comment]
@mreid21 Released in 2.10.0. Thanks for your contribution. Thanks for your patience. In the future, we will work to get PRs reviewed more quickly.

CC: @danielbuechele
